### ISSUE TITLE
Enrol page

### ISSUE THREAD

**Issue by Ramakrishnatp** [flyve-mdm/android-mdm-agent#308]
not able to go to enrol page

**Comment by rafaelje** [comment]
Hello @Ramakrishnatp! in order to try this app you need to install GLPI with the Flyve Plugin did you do it?

**Comment by Ramakrishnatp** [comment]
Just I have downloaded the code and run in android studio that it.

is it wrong or I need do any other steps , actually I getting walkthrough screen.

**Comment by rafaelje** [comment]
Don't worry please review this documentation first:

http://flyve.org/android-mdm-agent/howtos/getting-started

**Comment by Ramakrishnatp** [comment]
when I was  download app from play store it is working.
now I am working on your open source GitHub repo code .

**Comment by rafaelje** [comment]
At this moment with have two differents versión on Google Play

Legacy version:
https://play.google.com/store/apps/details?id=com.teclib.flyvemdm

New version:
https://play.google.com/store/apps/details?id=org.flyve.mdm.agent

I think you are working with the legacy version of the app

**Comment by Ramakrishnatp** [comment]
Thanks,
I am using https://github.com/flyve-mdm/android-mdm-agent git hub repo code and how to use it .

**Comment by rafaelje** [comment]
In order to use this MDM you need 2 things:

- (1) GLPI with Flyve MDM plugin
- (2) The Android Agent Flyve MDM

At this point, I think you just have the second one (Android Agent Flyve MDM) we are working on a public Dashboard demo of the first one (GLPI with Flyve MDM plugin) but is not complete today, we are working to release the Dashboard at the beginning of April

But if you want to try it now, you can install your own instance of GLPI with the plugin and start to use today.

This is the plugin repository:
- https://github.com/flyve-mdm/glpi-plugin 

And this is the Getting Started documentation:
- http://flyve.org/glpi-plugin/howtos/getting-started

**Comment by rafaelje** [comment]
after 23 days without a response, I'll close this issue, please @Ramakrishnatp fell free to re-open again if you need to
