### ISSUE TITLE
Inventory incomplete

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/android-mdm-agent#381]
#### Observed Results:

The XML sent to the backend is incomplete, information as software isn't available
  
#### Expected behavior:

The complete device inventory

**Comment by rafaelje** [comment]
This problem happend because the file size of the app is "0" or empty, I'm trying to find a way to get this file size but all that I found are a tricky way

https://stackoverflow.com/questions/28791461/ipackagestatsobserver-cannot-be-resolved-to-a-type-android

https://www-jo.se/f.pfleger/android-package-size

And other similar

**Comment by rafaelje** [comment]
These method to get the file size are asynchronous and is need to convert into synchronous

**Comment by rafaelje** [comment]
The inventory is complete with softwares tag but has fail on enrollment

**Comment by btry** [comment]
see #394 I'm pretty sure the xml is sent twice, leading to an invalid XML document.

**Comment by rafaelje** [comment]
the duplicated information and the software was added with the new library
