### ISSUE TITLE
FusionInventory agent not created

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-mdm-agent#504]
Hi, @rafaelje 
No inventory in the Web Dashboard.
No computer in the GLPI.
Agent said: Computer P2.
Error in the enrollment: FusionInventory agent not created

Inventory exported as XML and JSON.
[inventory-p2.zip](https://github.com/flyve-mdm/android-mdm-agent/files/2194494/inventory-p2.zip)

I can see the CDATA elements in the report in XML.
I think it's not supported by FusionInventory.
We need to submit a patch to FI /cc @g-bougard, @DIOHz0r, @btry 
Or debug in deep what happen.

References:

![image](https://user-images.githubusercontent.com/663460/42718546-32dcab24-870a-11e8-9cee-1fde1ec93cf8.png)

![image](https://user-images.githubusercontent.com/663460/42718528-135fd762-870a-11e8-9c07-07099ed58d1c.png)

**Comment by rafaelje** [comment]
This issue will be solved with this PR on the plugin https://github.com/flyve-mdm/glpi-plugin/pull/614

**Comment by rafaelje** [comment]
The problem was this:

The agent sent the inventory -> Fusion Inventory create the agent and return an ID number the plugin try to find a computer with this ID but fail in some case because the ID don't match, to solve this @DIOHz0r search the computer with the serial and not with the ID returned by FI
